### ISSUE TITLE
Dockerfile doesn't support other platforms (e.g., arm64/m1)

### ISSUE THREAD

**Issue by makslevental** [compiler-research/xeus-clang-repl#75]
In working around https://github.com/compiler-research/xeus-clang-repl/issues/74, I try to build the docker image (`docker build . -t xeus-clang-repl`) but fail to because of a linker error during building `CppInterOp`:

```
282.9 -- Build files have been written to: /home/jovyan/CppInterOp/build
282.9 ++ nproc --all
282.9 + cmake --build . --parallel 10
282.9 [  7%] Creating directories for 'googletest'
282.9 [  7%] Built target intrinsics_gen
...
314.8 [ 92%] Completed 'googletest'
314.9 [ 92%] Built target googletest
322.9 [ 92%] Built target obj.clangCppInterOp
322.9 [100%] Linking CXX shared library ../libclangCppInterOp.so
323.0 /usr/bin/ld.gold: error: /home/runner/work/xeus-clang-repl/xeus-clang-repl/clang-dev/inst/lib/libLLVMNVPTXCodeGen.a(NVPTXAsmPrinter.cpp.o): incompatible target
323.0 /usr/bin/ld.gold: error: /home/runner/work/xeus-clang-repl/xeus-clang-repl/clang-dev/inst/lib/libLLVMNVPTXCodeGen.a(NVPTXTargetMachine.cpp.o): incompatible target
323.0 /usr/bin/ld.gold: error: /home/runner/work/xeus-clang-repl/xeus-clang-repl/clang-dev/inst/lib/libLLVMNVPTXDesc.a(NVPTXMCTargetDesc.cpp.o): incompatible target
```

Not sure if it's because `gold` isn't smart enough or something else (i.e., I didn't try patching to use `ld` instead).

cc @vgvassilev

**Comment by mcbarton** [comment]
Not sure if this will help. The Dockerfile tags ubuntu-22.04, which  is for linux/amd64 (x86_64)( see https://hub.docker.com/r/jupyter/base-notebook/tags for the Docker base image page). If it was switched to latest then maybe you might have better luck, since this has arm64. 

In regards to your comment about using ld instead. It was needed when I installed xeus-clang-repl natively within MacOS on Apple Silicon. Assuming this project is interested in natively supporting arm64 I can create an issue on what changes were needed to install it natively, and eventually create pull requests (for both xeus-clang-repl and its dependencies).

**Comment by vgvassilev** [comment]
> Not sure if this will help. The Dockerfile tags ubuntu-22.04, which is for linux/amd64 (x86_64)( see https://hub.docker.com/r/jupyter/base-notebook/tags for the Docker base image page). If it was switched to latest then maybe you might have better luck, since this has arm64.
> 
> In regards to your comment about using ld instead. It was needed when I installed xeus-clang-repl natively within MacOS on Apple Silicon. Assuming this project is interested in natively supporting arm64 I can create an issue on what changes were needed to install it natively, and eventually create pull requests (for both xeus-clang-repl and its dependencies).

@mcbarton, that would be great - we are interested in this!

**Comment by mcbarton** [comment]
As I now need to look at the Dockerfile as part of my PR https://github.com/compiler-research/xeus-clang-repl/pull/77 I plan to solve this issue as part of the PR
